/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LamedeFeu (https://sketchfab.com/lamedefeu)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/windmill-game-ready-6a006afce57a447baa60c7a6791f0086
Title: Windmill (game ready)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function LightHouse(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/3d/windmill_game_ready.glb')
    const { actions } = useAnimations(animations, group)
    // Add animation for the windmill
    React.useEffect(() => {
        // Check if there are any animations
        if (actions && Object.keys(actions).length > 0) {
            console.log("Available animations:", Object.keys(actions));

            // Play all available animations
            Object.values(actions).forEach(action => {
                if (action && typeof action.play === 'function') {
                    action.play();
                }
            });

            // Clean up function to stop animations when component unmounts
            return () => {
                Object.values(actions).forEach(action => {
                    if (action && typeof action.stop === 'function') {
                        action.stop();
                    }
                });
            };
        } else {
            console.log("No animations found in the model");
        }
    }, [actions]);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group
                        name="ca383a8524684a959cd40c5276ee2149fbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Object_4">
                                    <primitive object={nodes._rootJoint} />
                                    <group name="RING" position={[-0.382, 2.493, 1.438]}>
                                        <mesh
                                            name="RING_standardSurface1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.RING_standardSurface1_0.geometry}
                                            material={materials.standardSurface1}
                                        />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/3d/windmill_game_ready.glb')
