/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Marco Zakaria (https://sketchfab.com/marcoZakaria)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-monitor-lowpoly-model-1d4ee42eda804b02b05b63721921c1d7
Title: Computer Monitor Lowpoly Model
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function MonitorScreen(props) {
  const { nodes, materials } = useGLTF(
    "/models/computer_monitor_lowpoly_model.glb"
  );
  // console.log(nodes.Object_4.geometry);
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.055, 0.3]}>
        <mesh
          castShadow
          receiveShadow
          // geometry={nodes.Object_4.geometry}
          // material={materials.Display}
          position={[0, 1.5, -0.24]}
        >
          <planeGeometry args={[3.74, 1.88, 2]} />
          {/* Background Color-Changing Effect */}
          <meshStandardMaterial map={props?.texture} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={props?.material}
        />
      </group>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Stand}
        position={[0, -0.055, 0.027]}
        rotation={[-1.571, 0, 0]}
        scale={0.272}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.Main_MAt}
      /> */}
    </group>
  );
}

useGLTF.preload("/models/computer_monitor_lowpoly_model.glb");
