/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: undernoon (https://sketchfab.com/undernoon)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/retrofuturistic-computer-13203a10d3694ab49bc8a53931d7b27e
Title: Retrofuturistic Computer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function RetroPc(props) {
  const { nodes, materials } = useGLTF("/models/3d//Sketchfab_Scene.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_3.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_55.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_56.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_57.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_58.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_59.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_60.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_61.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_62.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_63.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_64.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_65.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_66.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_67.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_68.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_69.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_70.geometry}
        material={materials.standardSurface3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_71.geometry}
        material={materials.standardSurface3}
      />
    </group>
  );
}

useGLTF.preload("/models/3d//Sketchfab_Scene.glb");
