/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ylitkaeksbitsionist (https://sketchfab.com/ylitkaeksbitsionist)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/touch-screen-ea67296e1efa4ac883dbcbfda8b77fa4
Title: Touch Screen
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function TouchScreen(props) {
    const { nodes, materials } = useGLTF('/models/3d/touch_screen.glb')
    return (
        <group {...props} dispose={null}>
            <group position={[0, -1.233, -0.024]} rotation={[Math.PI / 2, 0, 0]}>
                <group rotation={[-Math.PI, 0, 0]}>
                    <group position={[-0.116, -0.012, 0.616]} scale={0.01}>
                        <group position={[16.189, -25.554, -48.139]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Line0020000_Main_white_0.geometry}
                                material={materials.Main_white}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Line0020000_Main_white_0_1.geometry}
                                material={materials.Main_white}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Line0020000_Main_white_0_2.geometry}
                                material={materials.Main_white}
                            />
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Plane0050101_Main_white_0.geometry}
                            material={materials.Main_white}
                            position={[17.568, 13.968, 20.326]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object0020202_Main_white_0.geometry}
                            material={materials.Main_white}
                            position={[4.693, -0.02, 30.995]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object0132323_BMBY_0.geometry}
                            material={materials.BMBY}
                            position={[16.033, -26.297, -48.187]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Object0052424_Material_#28_0'].geometry}
                            material={materials.Material_28}
                            position={[10.118, 17.067, 21.211]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0124646_Metall_0.geometry}
                            material={materials.Metall}
                            position={[30.222, -38.829, 59.484]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0374747_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-25.66, -27.184, 17.87]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0364848_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-25.66, 26.6, 17.87]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Box0014949_Main_white_0.geometry}
                            material={materials.Main_white}
                            position={[1.083, -0.222, 30.531]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Box0889393_Main_white_0.geometry}
                            material={materials.Main_white}
                            position={[-5.4, 0, 34.569]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Box0875151_Rubber_black_0.geometry}
                            material={materials.Rubber_black}
                            position={[-23.259, -14.877, 16.775]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Box0885252_Rubber_black_0.geometry}
                            material={materials.Rubber_black}
                            position={[-23.182, -18.934, 16.664]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0015353_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-22.407, 20.888, 15.173]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0025454_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-22.407, 16.962, 15.173]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0035555_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-23.415, -12.811, 16.612]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0045656_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-23.415, -22.51, 16.612]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object0075757_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-23.616, 18.908, 17.587]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Shape0049292_Glass_0.geometry}
                            material={materials.Glass}
                            position={[-5.4, 0, 34.569]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object0085959_Rubber_black_0.geometry}
                            material={materials.Rubber_black}
                            position={[-23.182, -18.934, 16.664]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0056060_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-40.771, -1.082, 9.775]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0068989_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-40.771, -73.305, 9.775]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0076262_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-40.771, -38.829, 9.775]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0086363_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-40.771, 34.781, 9.775]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0096464_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-40.771, 73.868, 9.775]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0106565_Metall_0.geometry}
                            material={materials.Metall}
                            position={[30.222, -1.082, 59.484]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0118888_Metall_0.geometry}
                            material={materials.Metall}
                            position={[30.222, -73.305, 59.484]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0386767_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-25.66, -12.116, 17.87]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0136868_Metall_0.geometry}
                            material={materials.Metall}
                            position={[30.222, 34.781, 59.484]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0146969_Metall_0.geometry}
                            material={materials.Metall}
                            position={[30.222, 73.868, 59.484]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0157070_Metall_0.geometry}
                            material={materials.Metall}
                            position={[28.38, 75.858, 58.195]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0167171_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-39.031, 75.858, 10.993]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0177272_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-5.799, 75.858, 34.263]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0188787_Metall_0.geometry}
                            material={materials.Metall}
                            position={[28.38, -75.881, 58.195]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0198686_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-39.031, -75.881, 10.993]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0209494_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-5.799, -75.881, 34.263]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0217676_Metall_0.geometry}
                            material={materials.Metall}
                            position={[21.87, -26.963, 51.151]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0227777_Metall_0.geometry}
                            material={materials.Metall}
                            position={[21.87, 26.066, 51.151]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0237878_Metall_0.geometry}
                            material={materials.Metall}
                            position={[19.489, 28.822, 49.484]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0247979_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-23.549, 28.822, 19.348]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0258080_Metall_0.geometry}
                            material={materials.Metall}
                            position={[0.828, 28.822, 36.417]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0268181_Metall_0.geometry}
                            material={materials.Metall}
                            position={[19.489, -29.402, 49.484]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0278282_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-23.549, -29.402, 19.348]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0288383_Metall_0.geometry}
                            material={materials.Metall}
                            position={[0.828, -29.402, 36.417]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0298484_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-23.549, 9.085, 19.348]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0307575_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-16.501, 9.085, 24.283]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0317474_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-16.501, -0.562, 24.283]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0327373_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-23.549, -9.913, 19.348]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0336666_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-16.501, -9.913, 24.283]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Sphere0356161_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-25.66, 11.532, 17.87]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object0149090_Frame_0.geometry}
                            material={materials.Frame}
                            position={[-5.4, 0, 34.569]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object0159191_Screen_0.geometry}
                            material={materials.Screen}
                            position={[-5.4, 0, 34.569]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object0165858_Usb_in_0.geometry}
                            material={materials.Usb_in}
                            position={[-23.616, 18.908, 17.587]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object0175050_Rubber_black_0.geometry}
                            material={materials.Rubber_black}
                            position={[-23.616, 18.908, 17.587]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object0188585_button_0.geometry}
                            material={materials.button}
                            position={[-23.259, -14.877, 16.775]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Shape53334_Rubber_black_0.geometry}
                            material={materials.Rubber_black}
                            position={[-23.616, 18.908, 17.587]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0030404_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[29.044, 16.374, 46.904]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0020505_Metall_0.geometry}
                            material={materials.Metall}
                            position={[29.046, 16.545, 46.905]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0010606_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[29.046, 28.093, 46.905]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0040808_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[29.046, -28.136, 46.905]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0050909_Metall_0.geometry}
                            material={materials.Metall}
                            position={[29.046, -16.588, 46.905]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0061010_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[29.044, -16.417, 46.904]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0091212_Metall_0.geometry}
                            material={materials.Metall}
                            position={[16.295, 15.888, 20.859]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0071313_Metall_0.geometry}
                            material={materials.Metall}
                            position={[16.306, 17.195, 20.843]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0101515_Metall_0.geometry}
                            material={materials.Metall}
                            position={[16.298, -17.599, 20.843]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0111616_Metall_0.geometry}
                            material={materials.Metall}
                            position={[16.308, -16.292, 20.859]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0121818_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-8.224, 16.904, 21.716]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0131919_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-8.235, 16.548, 21.732]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0142121_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-8.232, -17.288, 21.716]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0152222_Metall_0.geometry}
                            material={materials.Metall}
                            position={[-8.222, -16.931, 21.732]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Circle0032727_Cooper_0.geometry}
                            material={materials.Cooper}
                            position={[-3.9, 16.602, 21.75]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Shape0032828_Rubber_black_0.geometry}
                            material={materials.Rubber_black}
                            position={[0.511, 16.451, 21.535]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Line0062929_Cooper_0.geometry}
                            material={materials.Cooper}
                            position={[8.526, 16.454, 21.231]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Circle0043131_Cooper_0.geometry}
                            material={materials.Cooper}
                            position={[-3.9, -16.997, 21.75]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Line0073232_Cooper_0.geometry}
                            material={materials.Cooper}
                            position={[8.526, -16.849, 21.231]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Shape0053333_Rubber_black_0.geometry}
                            material={materials.Rubber_black}
                            position={[0.511, -16.847, 21.535]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0183535_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[13.882, 24.916, 38.993]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0163636_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[13.925, 24.918, 38.924]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0193838_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[-16.625, 24.918, 17.489]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0203939_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[-16.668, 24.916, 17.558]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0214141_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[13.925, -25.016, 38.924]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0224242_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[13.882, -25.018, 38.993]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0234444_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[-16.625, -25.016, 17.489]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder0244545_Metall_black_0.geometry}
                            material={materials.Metall_black}
                            position={[-16.668, -25.018, 17.558]}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/3d//touch_screen.glb')
